# Site settings
author: Kat B
title: 
header-img: img/home-bg.png
email: katreesebarnes@gmail.com
copyright_name: Kat B
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: thekatreesian
github_username:  katreesedarcene

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
